#!/usr/bin/env bash
# Pal - One-click install script
# Usage: bash install.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

echo ""
echo "  Pal - AI Role-Playing Chat Framework"
echo "  Installer"
echo "  ====================================="
echo ""

# ── Python deps ──
echo "[1/4] Installing Python dependencies..."
PYTHON=""
for py in python3 python3.12 python3.11 python3.10 python; do
    command -v "$py" &>/dev/null && PYTHON="$py" && break
done

if [ -z "$PYTHON" ]; then
    echo "  ERROR: Python 3 not found. Please install Python 3.10+."
    exit 1
fi
echo "  Python: $($PYTHON --version)"

PIP="$PYTHON -m pip"
$PIP install --break-system-packages -q textual flask requests python-dotenv Pillow 2>/dev/null || \
$PIP install --user -q textual flask requests python-dotenv Pillow 2>/dev/null || \
$PIP install -q textual flask requests python-dotenv Pillow 2>/dev/null
echo "  Dependencies installed."

# ── Create directories ──
echo "[2/4] Creating project structure..."
mkdir -p "$PROJECT_ROOT/ui"
mkdir -p "$PROJECT_ROOT/agent"
mkdir -p "$PROJECT_ROOT/file"
mkdir -p "$PROJECT_ROOT/workspace"
echo "  Directories ready."

# ── Generate banner if missing ──
if [ ! -f "$PROJECT_ROOT/core/banner.txt" ]; then
    echo "  Generating default banner..."
    cat > "$PROJECT_ROOT/core/banner.txt" << 'BANNER'
   ██████╗  █████╗ ██╗
   ██╔══██╗██╔══██╗██║
   ██████╔╝███████║██║
   ██╔═══╝ ██╔══██║██║
   ██║     ██║  ██║███████╗
   ╚═╝     ╚═╝  ╚═╝╚══════╝
BANNER
fi

# ── Generate ui.sh ──
echo "[3/4] Generating ui.sh launcher..."
UI_LAUNCHER="$PROJECT_ROOT/ui.sh"
cat > "$UI_LAUNCHER" << 'UISH'
#!/usr/bin/env bash
# Pal UI Launcher - Auto-generated by install.sh
cd "PROJECT_ROOT_PLACEHOLDER"
python3 -c "from ui.tui import main; main()"
UISH
# Replace placeholder with actual path
sed -i "s|PROJECT_ROOT_PLACEHOLDER|$PROJECT_ROOT|g" "$UI_LAUNCHER"
chmod +x "$UI_LAUNCHER"
echo "  ui.sh generated at $UI_LAUNCHER"

# ── Global pal command ──
echo "[4/4] Setting up global 'pal' command..."
mkdir -p "$HOME/bin"
cat > "$HOME/bin/pal" << 'WRAPPER'
#!/usr/bin/env bash
cd "$PROJECT_ROOT" && python3 main.py "$@"
WRAPPER
chmod +x "$HOME/bin/pal"

cat > "$HOME/bin/pal-ui" << 'UIWRAP'
#!/usr/bin/env bash
exec bash "$PROJECT_ROOT/ui.sh"
UIWRAP
chmod +x "$HOME/bin/pal-ui"

# Add to PATH if needed
if ! echo "$PATH" | grep -q "$HOME/bin"; then
    echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"
fi

echo ""
echo "  ====================================="
echo "  Installation complete!"
echo ""
echo "  Start UI:       bash $PROJECT_ROOT/ui.sh"
echo "  CLI:            pal --help"
echo "  Create agent:   pal create mybot --wizard"
echo "  ====================================="
echo ""
